// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageData } from "./MessageData";

export type Message = { "Broadcast": number } | { "Hello": MessageData } | { "Text": MessageData } | { "Image": MessageData } | { "Ack": { uid: number, mid: number, } };