// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MessageData { name: string, uid: bigint, mid: bigint, timestamp: bigint, payload: Array<number>, }