// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageData } from "./MessageData";

export type Message = { "Text": MessageData } | { "Image": MessageData } | { "Hello": MessageData } | { "Ack": { mid: number, uid: number | null, } };