// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Profile { name: string, uid: bigint, join_time: bigint, pic: Array<number>, }